set -g mouse on            # enable full mouse support
set -g renumber-windows on # ensure window index numbers get reordered
set -g base-index 1 	     # start windows and panes index at 1 not 0

setw -g mode-keys vi       # enable vi commands
setw -g pane-base-index 1  # start windows at 1
set -g history-limit 50000

# Puglins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'christoomey/vim-tmux-navigator'

# Use Ghostty's native TERM (best compatibility)
set -g default-terminal "xterm-ghostty"

# Truecolor / RGB support
set -ag terminal-overrides ",xterm-ghostty:RGB"
set -ag terminal-features ",xterm-ghostty:RGB"

# FORÇAR transparência nos painéis e na barra de status
set -g window-style 'bg=default'
set -g window-active-style 'bg=default'
set -g pane-border-style 'bg=default'
set -g pane-active-border-style 'bg=default'
set -g status-style 'bg=default' # Deixa a barra inferior transparente também


# set-option -g default-command "reattach-to-user-namespace -l $SHELL"


# Bindings   
set -g prefix C-a         
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h


unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z # m key maximize panel size

# Run
run '~/.tmux/plugins/tpm/tpm' # keep this line at the very bottom of tmux.conf
